name: Sync Notes and Images to Docusaurus Repo

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest  # Uses a Linux environment

    steps:
      # Step 1: Checkout the Source Repository
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      # Step 2: Checkout the Docusaurus Repository
      - name: Checkout Docusaurus Repo
        uses: actions/checkout@v2
        with:
          repository: Edumonkeys/Docs  # Replace with your actual Docusaurus repo
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          path: Docs  # The folder where the Docusaurus repo is cloned

      # Step 3: Sync Notes to Docusaurus Docs
      - name: Sync Notes to Docusaurus Docs
        run: |
          echo "Syncing notes to Docusaurus docs..."
          rsync -av --delete notes/ Docs/my-website/docs/
          echo "Notes synced successfully!"

      # Step 4: Sync Images to Docusaurus Static Folder
      - name: Sync Images to Docusaurus Static Folder
        run: |
          echo "Syncing images to Docusaurus static folder..."
          rsync -av --delete img/ Docs/my-website/static/img/
          echo "Images synced successfully!"

      # Step 5: Commit and Push Changes to the Docusaurus Repo
      - name: Commit Changes to Docusaurus Repo
        run: |
          cd Docs  # Enter the Docusaurus repo directory
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .  # Stage all changes
          git diff --cached --quiet || git commit -m "Sync notes and images from source repo"
          git push origin main || echo "No changes to push"
