name: Sync Notes and Images to Docusaurus Repo

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest  # Uses a Linux environment

    steps:
      # Step 1: Checkout the Source Repository
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      # Step 2: Checkout the Docusaurus Repository
      - name: Checkout Docusaurus Repo
        uses: actions/checkout@v2
        with:
          repository: Edumonkeys/Docs  # Replace with your actual Docusaurus repo
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          path: Docs  # The folder where the Docusaurus repo is cloned

      # Step 3: Sync Notes to Docusaurus Docs
      - name: Sync Notes to Docusaurus Docs
        run: |
          rsync -av --delete notes/ docusaurus-repo/my-website/docs/  # Sync 'notes/' to 'my-website/docs/'

      # Step 4: Sync Images to Docusaurus Static Folder
      - name: Sync Images to Docusaurus Static Folder
        run: |
          rsync -av --delete img/ docusaurus-repo/my-website/static/img/  # Sync 'img/' to 'my-website/static/img/'

      # Step 5: Commit Changes to the Docusaurus Repo
      - name: Commit Changes to Docusaurus Repo
        run: |
          cd docusaurus-repo  # Enter the Docusaurus repo directory
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .  # Stage all changes
          git commit -m "Sync notes and images from source repo" || echo "No changes to commit"  # Commit only if there are changes
          git push origin main  # Push changes to the Docusaurus repo
